name: "cmake-clang-ninja-build"
description: "Build CMake projects using Clang and Ninja"
inputs:
  dir:
    description: "Directory containing top level CMakeLists.txt"
    required: true
    default: "src"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dir }}
